### PR TITLE
Update recommended-inline-policy

### PR DESCRIPTION
**Pull request by amolsr**
Description of changes:
The following premission were requested by the ack of eks.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — COMMENTED** [review]
@amolsr is there a particular document that prompted this pull request? I'm wondering why the ACK controller for EKS would need permission to call IAM's PassRole or ListAttachedRolePolicies or EC2's DescribeSubnets. Remember that the ACK controller needs permissions only to communicate with the specific AWS API endpoints that it will communicate with. The ACK controller for EKS does not call IAM or EC2 endpoints...

**Comment by amolsr** [comment]
`apiVersion: eks.services.k8s.aws/v1alpha1
kind: Nodegroup
metadata:
  name: nodegroup
spec:
  amiType: "AL2_x86_64"
  capacityType: "ON_DEMAND"
  clusterName: $(clusterName)
  diskSize: 100
  instanceTypes:
  - "m5.2xlarge"
  labels: {node : "vcpu", type : "ON_DEMAND", project : $(profile)}
  name: $(environment)-$(profile)-nodegroup
  nodeRole: arn:aws:iam::xxxx:role/xxxx
  scalingConfig: 
    desiredSize: 2
    maxSize: 6
    minSize: 2
  subnets:
  - $(primarySubnet)
  - $(secondarySubnet)
  tags: { environment: $(environment), project_name: $(profile) }
  taints:
  - effect: "NO_SCHEDULE"
    key: "project"
    value: $(profile)
`

I was using above specified yaml for creating a nodegroup. The EKS controller version I am using is the one present in main. The log of the eks-controller pod had prompted me to add those permissions as well.

**Comment by jaypipes** [comment]
> ```
> kind: Nodegroup
> metadata:
>   name: nodegroup
> spec:
>   amiType: "AL2_x86_64"
>   capacityType: "ON_DEMAND"
>   clusterName: $(clusterName)
>   diskSize: 100
>   instanceTypes:
>   - "m5.2xlarge"
>   labels: {node : "vcpu", type : "ON_DEMAND", project : $(profile)}
>   name: $(environment)-$(profile)-nodegroup
>   nodeRole: arn:aws:iam::xxxx:role/xxxx
>   scalingConfig: 
>     desiredSize: 2
>     maxSize: 6
>     minSize: 2
>   subnets:
>   - $(primarySubnet)
>   - $(secondarySubnet)
>   tags: { environment: $(environment), project_name: $(profile) }
>   taints:
>   - effect: "NO_SCHEDULE"
>     key: "project"
>     value: $(profile)
> ```
> 
> I was using above specified yaml for creating a nodegroup. The EKS controller version I am using is the one present in main. The log of the eks-controller pod had prompted me to add those permissions as well.

@amolsr What you are referring to above (and in this PR's content) is the [EKS node create Role](https://docs.aws.amazon.com/eks/latest/userguide/create-node-role.html), not the Role associated with the Kubernetes ServiceAccount running the ACK eks-controller.

**Comment by amolsr** [comment]
This is the role I am using with the service account of aws-eks-controller, not the one which will be associated with eks nodegroup after the applying the above yaml.

**Comment by jaypipes** [comment]
> This is the role I am using with the service account of aws-eks-controller, not the one which will be associated with eks nodegroup after the applying the above yaml.

Yes, and I am saying that that role you are associating with the service account running the eks-contorller does *not* need those permissions in order to properly operate.

Best,
jay

**Comment by amolsr** [comment]
Okay, Let me check at my end then.

**Pull request closed without merging**
