### PR TITLE
Generate `AccessEntry` resource.

### PR DESCRIPTION
**Pull request by a-hilaly**
This commit upgrades the aws-sdk to version 1.49.13, enabling the
generation of the new `AccessEntry` resource. The primary enhancements
include:

- Integration of `AccessEntry` generation from sdk 1.49.13
- Introduction of the `AccessPolicies` field within `AccessEntry.Spec`
- Implementation of custom hooks to handle policy [dis]associations and tag
   updates.
- Addition of exhaustive e2e tests covering diverse create and update
  scenarios

Signed-off-by: Amine Hilaly <hilalyamine@gmail.com>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by a-hilaly** [comment]
Need #88 to set `AccessConfig` in the test cluster.
/hold

**Review by jonathan-innis — APPROVED** [review]
/lgtm

**Pull request merged**
