### PR TITLE
AWS Go SDK up v1.42.28

### PR DESCRIPTION
**Pull request by yandooo**
Issue https://github.com/aws-controllers-k8s/community/issues/1283, if available:

Description of changes: update AWS Go SDK version to v.1.42.28 (to use in Crossplane AWS provider project)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by vijtrip2 — COMMENTED** [review]
/ok-to-test

**Comment by vijtrip2** [comment]
hey @yandooo , this PR looks good. But would you be able to add an e2e test as well for this new field?
If not, then I can do it as well, but later.

The e2e tests reside in test/e2e/tests directory. Having an e2e test will give us confidence to make the new release.

**Comment by yandooo** [comment]
@vijtrip2 not sure why e2e is in python, but also it looks like not mocked but rather needs real AWS env to test it out. It's great but goes beyond the timeframe I can allocate to get it done. If you could give a hand it is appreciated.

**Comment by jaypipes** [comment]
> @vijtrip2 not sure why e2e is in python, but also it looks like not mocked but rather needs real AWS env to test it out. It's great but goes beyond the timeframe I can allocate to get it done. If you could give a hand it is appreciated.

@vijtrip2 looking through the code changes, looks like just a single string field `Spec.KubernetesNetworkConfig.IPFamily` was added. I'd be OK pushing this through without an e2e test since it's a small, no-risk change.

**Comment by vijtrip2** [comment]
> looking through the code changes, looks like just a single string field Spec.KubernetesNetworkConfig.IPFamily was added. I'd be OK pushing this through without an e2e test since it's a small, no-risk change.

Sounds good, Jay! I will add an e2e test for this after the PR merges(since it creates an ipv6 cluster, there may be something hidden that we may need to handle), and then cut a new release very soon for eks-controller. @yandooo , thanks for your contribution and patience : )

**Pull request merged**
